project:
  type: website
  output-dir: docs  

website:
  title: "London SDE/AIC Technical Documentation"
  navbar:
    background: secondary
  sidebar: 
    style: "docked"
    search: false
    contents:
      - section: "MAIN"
        contents: 
          - href: index.qmd
            text: Home
      - section: "COMMON DATA MODEL"
        contents: 
          - href: pages/data_model/cdm_person.qmd
            text: Table/PERSON
          - href: pages/data_model/cdm_condition_occurrence.qmd
            text: Table/CONDITION_OCCURRENCE
          - href: pages/data_model/cdm_drug_exposure.qmd
            text: Table/DRUG_EXPOSURE
          - href: pages/data_model/cdm_measurement.qmd
            text: Table/MEASUREMENT                        
          - href: pages/data_model/notes_provenance.qmd
            text: Notes/Data Provenance                           
                     
format:
  html:
    theme: zephyr
    mermaid:
      theme: neutral
